// <auto-generated />
namespace PCA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1228fiximagesatempt1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1228fiximagesatempt1));
        
        string IMigrationMetadata.Id
        {
            get { return "201612281606066_12-28-fix-images-atempt1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
