// <auto-generated />
namespace PCA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1192017dailyreportdelay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1192017dailyreportdelay));
        
        string IMigrationMetadata.Id
        {
            get { return "201701191821536_1-19-2017dailyreportdelay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
